//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class type_request
    {
        public type_request()
        {
            this.type_incident = new HashSet<type_incident>();
            this.type_sh = new HashSet<type_sh>();
        }
    
        public int tid { get; set; }
        public int rid { get; set; }
        public string tname { get; set; }
    
        public virtual request request { get; set; }
        public virtual ICollection<type_incident> type_incident { get; set; }
        public virtual ICollection<type_sh> type_sh { get; set; }
    }
}
