//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class type_incident
    {
        public int incid { get; set; }
        public int tid { get; set; }
        public string incname { get; set; }
    
        public virtual type_request type_request { get; set; }
    }
}
